### ISSUE TITLE
Change name layout.

### ISSUE THREAD

**Issue by kerrtrvs** [kerrtrvs/www#1]
![1](https://user-images.githubusercontent.com/26391179/45434158-a5a96000-b6a5-11e8-9c38-331c19891336.png)

I'd rather change this to just `kerrtrvs` or `kerr`, the `@` needs to go.

I'll look into what looks best and fits with the text placement below the name.

**Comment by kerrtrvs** [comment]
Fixed.

**Comment by IamTregsthedev** [comment]
Um kerr, I might have delated u from my discord. Please give you tag thanks :D
